---
title: "Monte Carlo Simulation"
author: "Ahmed Tijani Akinfalabi"
date: "10-01-2024"
output: html_document
---

#```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
#```


```{r fig=TRUE,fig.width=16,fig.height=9, eval=FALSE}
set.seed(123)
source('beesim.R')
par(mfrow=c(2,3),mai=c(0.2,0.2,0.7,0.1))

BeeSim$new(20)   # create 20 agents
BeeSim$drawBeetles()
BeeSim$iter()
for (i in 1:5) { BeeSim$iter() }
BeeSim$drawBeetles()

for (i in 1:10) { BeeSim$iter() ; BeeSim$mating()}
BeeSim$drawBeetles()

for (i in 1:35) { BeeSim$iter(debug=FALSE) ; BeeSim$mating(debug=FALSE)}
BeeSim$drawBeetles()

for (i in 1:35) { BeeSim$iter(debug=FALSE) ; BeeSim$mating(debug=FALSE)}
BeeSim$drawBeetles()

BeeSim$plotMonitor()
```


```{r}
set.seed(123)

n = 20
beetles=data.frame(x=runif(n,min=0,max=50),
                  y=runif(n,min=0,max=50),
                  sex=c("F","M")[rbinom(n,1,p=0.5)+1],
                  color=c("red","orange")[rbinom(n,1,p=c(0.8,0.2))+1],
                  points=sample(4:7,n,replace=TRUE),
                  age=sample(0:5,n,replace=TRUE),
                  energy=rep(10,n))

beetles

gender = table(beetles$sex)
gender    # I realized the number of females are more than the male. 3:1

food=data.frame(x=c(rnorm(10,mean=12,sd=5),rnorm(20,mean=42,sd=5),runif(20,0,50)),
               y=c(rnorm(10,mean=12,sd=5),rnorm(20,mean=42,sd=5),runif(20,0,50)),
               age=rep(0,50))
  
food

monitor=data.frame(iter=0,beetles=nrow(beetles),food=nrow(food))

monitor  
```


```{r fig=TRUE,fig.width=16,fig.height=9}
set.seed(123)
source('beesim.R')
par(mfrow=c(2,3),mai=c(0.2,0.2,0.7,0.1))
BeeSim$new(20)   # create 20 agents
BeeSim$drawBeetles()
BeeSim$iter()
for (i in 1:5) { BeeSim$iter() }
BeeSim$drawBeetles()
for (i in 1:10) { BeeSim$iter() ; BeeSim$mating()}
BeeSim$drawBeetles()
for (i in 1:35) { BeeSim$iter(debug=FALSE) ; BeeSim$mating(debug=FALSE)}
BeeSim$drawBeetles()
for (i in 1:35) { BeeSim$iter(debug=FALSE) ; BeeSim$mating(debug=FALSE)}
BeeSim$drawBeetles()
BeeSim$plotMonitor()
```
